### ISSUE TITLE
Improve syntax highlighting styles

### ISSUE THREAD

**Issue by mkroetzsch** [knowsys/rulewerk-eclipse#13]
The styles used for syntax highlighting should be improved. Main general guidelines:

- Use normal text for highly common content, such as predicate names, and avoid an overly colourful appearance (right now, most of of my files are in bold orange!)
- Use known Java styles for elements that play a similar role

Concretely, this can be implemented in the following changes:

- all directives (everything starting with ```@```) should look exactly like Java's ```public```
- universal variables should look like local variables in Java
- Comments should look like normal (non-JavaDoc) comments
- Strings should look like Java string constants. This should include the language tag if present.
- prefixed names and names without prefixes should be in normal font
- prefixes in the prefix declaration should be formatted like the member variables of a Java class

However, the following should deviate from Java:
- numerical constants should be styled like strings, even when using the short form without quotes
- boolean constants should be styled like strings, even when using the short form without quotes
- full IRIs in ```< ... >``` should be formatted in mildly coloured style, maybe some dark violet (but not in bold)
- Logical connectives such as ```:-```, ```~```, and ```,```, and the final ```.``` should be in bold (but black); note that this should not apply to commas used in arguments of literals

**Comment by alloka** [comment]
?Dear Markus,


I pushed the changes, please let me know if there is something else regarding syntax highlighting.



Best Regards,

Ali.

________________________________

**Comment by mkroetzsch** [comment]
Are these really the same colours as in your Eclipse Java? In my Eclipse version, the colours look similar but are not the same. For example, inline comments in my Java are #3f7f5f whereas comments in rls are #228a22. There are also differences for other colours that were meant to be the same as in Java.

As I wrote above, prefixed names should be in normal font. They are still orange.

The colour for full IRIs is "some dark violet" alright, but it now is the almost the same colour as for @directives, which is distracting in ```@prefix``` declarations. Please use another colour that is also somewhat darker still.

The rest looks good to me now.

P.S. Please use github to have this conversation (link below each email). Your email-based replies are strangely formatted in the public web pages and start with a "?".

**Comment by alloka** [comment]
I try to make it similar to the java colors as much as I can, I don't know how to obtain the colors codes exactly, I fixed the changes you mentioned in your comment and if you have any further remarks please let me know

**Comment by mkroetzsch** [comment]
Getting colours from the screen is easy. Google can help you there. However, you can also get the exact colours from the Eclipse settings.

**Comment by alloka** [comment]
Done
