### ISSUE TITLE
Errors do not appear in "Problems" view

### ISSUE THREAD

**Issue by mkroetzsch** [knowsys/rulewerk-eclipse#4]
Errors in RLS files should appear in the "Problems" view of Ecplise. Currently, they are not shown there.

**Comment by alloka** [comment]
Dear Markus,


are you sure of this?, I just tried making an error (existential variable in body) and it appears in the errors view for me, as well as the markers view.


Best Regards,

Ali.

________________________________

**Comment by mkroetzsch** [comment]
Yes, I am sure of this. The problem remained after a complete re-installation from github. See screenshot. I am talking about the ```Problems``` view. There is also an ```Error Log``` view. I do not have an ```errors view``` or a ```markers view``` in my Eclipse (under Window->Show View).


![Screenshot](https://user-images.githubusercontent.com/110881/94376301-0c2d3980-011a-11eb-9f34-d2f297095174.png)

**Comment by alloka** [comment]
?Dear Markus,


Kindly find the screenshot from my eclipse attached.


Best Regards,

Ali.

________________________________

**Comment by alloka** [comment]
?Do you have the others option in show view ?

________________________________

**Comment by alloka** [comment]
@mkroetzsch please check commit a96dc7b7e9afd424d68bd41cf20fdc000841a8e8 for a fix for this problem
