### ISSUE TITLE
 Syntax highlighting fails on @import

### ISSUE THREAD

**Issue by mkroetzsch** [knowsys/rulewerk-eclipse#7]
The correct input
```
@import "rules.rls" .
```
is not accepted by the Eclipse plugin. An error appears at ```@import```. From this point on, syntax highlighting does not work for the remaining file either.

**Comment by alloka** [comment]
?Dear Markus,


The original grammar has a problem which is that the token of the parse rule langtag is sometimes mixed with the token of directive, this problem should also be discussed with max, but as a temporary solution, I can disable the rule of the langtag if you are not using it in the demo.


Best Regards,

Ali.

________________________________

**Comment by mkroetzsch** [comment]
This import is parsed correctly in Rulewerk, so I do not think that the problem is with Rulewerk's grammar as such. Maybe you need to represent it differently in the Eclipse plugin to work correctly? At the beginning of a statement (right after a . in the previous line), an ```@``` symbol should never be parsed as a language tag. Language tags can only occur after strings.

**Comment by alloka** [comment]
?Yes, I understand that, but I'm quite sure that langtag and directives have interleaving tokens, but the way tokens are handled in javacc is that you can state which rules exactly do you want the tokens to work for, and unfortunately it is not that way in xtext grammar.


Best Regards,

Ali.

________________________________

**Comment by alloka** [comment]
?I mean that in the original grammar they do have interleaving tokens, but it is mentioned that langtag works for specifc rules and directives for others.?

________________________________

**Comment by mkroetzsch** [comment]
After the recent changes, ```@import``` works but language tagged string now fail. I will close this bug report and make anew one for the new issue.
