### ISSUE TITLE
Support creation of Rulewerk files

### ISSUE THREAD

**Issue by mkroetzsch** [knowsys/rulewerk-eclipse#9]
The plugin should add new file types to Eclipse, so that users can create new rls files using the "New" context menu.

**Comment by alloka** [comment]
@mkroetzsch check the latest commit please

**Comment by mkroetzsch** [comment]
The best way to solicit a code review is to create a pull request and to invite reviewers there. If you have already pushed to master, you could add a link to the commit I should check in this chat.

**Comment by alloka** [comment]
Ok, starting next time I will do a pull request, https://github.com/knowsys/rulewerk-eclipse/commit/81bd612e741f59e6f15c12ea730ac3f6203269a4 this is the link to the commit of the issue fixing

**Comment by alloka** [comment]
@mkroetzsch please check commit d44dcca05aa4f3eed215cafedf6ef8b4480c1efb for the final presentation of this feature

**Comment by alloka** [comment]
@mkroetzsch check 25e34b821ca375bd2ea1fcfbf33fcda3bd515c28 for final review
